### PR TITLE
Update scripts.php

### PR DESCRIPTION
**Pull request by mhimon**
Added: editor.css

### CODE REVIEW

**Comment by asaquzzaman** [comment]
@mhimon 

Good job brother. Hope you will continue it.

**Comment by mhimon** [comment]
Thanks. I am doing because I love weDevs and Tareq & Nizam Bhai <3

**Comment by asaquzzaman** [comment]
@mhimon 

You love weDevs, Tareq and Nizam but not me. :'( 
Just joking, really both of are great people and i feel proud as a part of weDevs.

Thanks

**Comment by mhimon** [comment]
haha! yes, they are great! I would be happy to work with weDevs but I am
not that much expert yet and still learning. I am from a village located in
Pabna so also not able to go to the office. Also as a college student, it's
not possible to go to Dhaka now.

**Comment by asaquzzaman** [comment]
@mhimon 

May i have your mobile number please? Its me joy.mishu@gmail.com

**Comment by mhimon** [comment]
check mail <3

**Comment by mhimon** [comment]
@asaquzzaman bro lemme know if you get that mail, Thanks :)

**Pull request merged**
